### ISSUE TITLE
Add another developer to the about us page

### ISSUE THREAD

**Issue by jeshmi-hub** [Ankush-Khatiwada/LibraryManagementSystem#5]
Add bhuwan Pandit too in the about us page in the our team section

**Comment by Ankush-Khatiwada** [comment]
Our new developer has been added and issue hasbeen solved

![Screenshot from 2021-04-16 10-40-13](https://user-images.githubusercontent.com/70217925/114973525-5c929b80-9ea0-11eb-80e7-f7029ca2e3ec.png)
