### ISSUE TITLE
Space Missing at Nav bar. between about us and contact us.

### ISSUE THREAD

**Issue by bpandit111** [Ankush-Khatiwada/LibraryManagementSystem#8]
Add space between about us and contact us at navigation bar.

**Comment by Ankush-Khatiwada** [comment]
![Screenshot from 2021-04-16 11-12-46](https://user-images.githubusercontent.com/70217925/114975877-b09f7f00-9ea4-11eb-9421-641f1ea0ebf7.png)
The issue has been solved
