### ISSUE TITLE
Footer issue at Admin Page.

### ISSUE THREAD

**Issue by bpandit111** [Ankush-Khatiwada/LibraryManagementSystem#9]
Footer is not at the bottom of the page when we go to admin page, however other page are fine.
![viber_image_2021-04-16_10-14-58](https://user-images.githubusercontent.com/82435806/114971760-c90b9b80-9e9c-11eb-8577-540ed978945c.jpg)

**Comment by Ankush-Khatiwada** [comment]
![Screenshot from 2021-04-16 11-11-03](https://user-images.githubusercontent.com/70217925/114975736-7b932c80-9ea4-11eb-819c-312596af5052.png)
issue has been solved
